
import ontologies.org.w3._1999._02._22_rdf_syntax_ns as rdf
import ontologies.org.w3._2000._01.rdf_schema as rdfs
import ontologies.org.schema as schemaorg1
import ontologies.com.xmlns.foaf._0_1 as foaf
import ontologies.org.vocab.open.terms as ov
import ontologies.org.w3._2004._02.skos.core as skos
import ontologies.org.w3._2002._07.owl as owl
import ontologies.org.schema as schemaorgs
import ontologies.org.purl.dc.terms as dc
import ontologies.org.w3._2003._06.sw_vocab_status.ns as vs
import ontologies.org.w3._2007._05.powder_s as wdrs
import ontologies.org.w3._2002._12.cal.icalSpec as spec
import ontologies.org.w3.ns.ui as ui
import ontologies.org.w3.ns.auth.cert as authcert
import ontologies.org.purl.dc.elements._1_1 as dct
import ontologies.org.creativecommons.ns as cc
import ontologies.org.w3._1999.xhtml.vocab as html
import ontologies.org.w3.ns.posix.stat as posix
import ontologies.org.w3.ns.ldp as ldp
import ontologies.org.purl.dc.dcam as dcam
import ontologies.gov.loc.mads.rdf.v1 as mads
import ontologies.org.w3.ns.auth.acl as acl
import ontologies.org.purl.vocab.vann as vann
import ontologies.org.w3._2006.vcard.ns as vcard2006
import ontologies.org.w3.ns.pim.space as space
import ontologies.org.purl.goodrelations.v1 as gr
import ontologies.org.w3._2003._01.geo.wgs84_pos as wgs84
import ontologies.org.purl.vocab.changeset.schema as changeset
import ontologies.gov.loc.id.ontologies.RecordInfo as recordinfo
import ontologies.org.w3._2000._10.swap.pim.contact as pim
import ontologies.org.rddl.purposes as rddl
import ontologies.org.w3._2008._05.skos_xl as skosxl
import ontologies.ie.deri.vocab.void as void2
import ontologies.com.usefulinc.ns.doap as doap
import ontologies.org.purl.vocommons.voaf as voaf
import ontologies.org.rdfs.sioc.services as siocs
import ontologies.org.w3._2000._10.swap.pim.doc as doc
import ontologies.gov.loc.id.vocabulary.identifiers as vocab
import ontologies.org.w3.ns.adms as adms
import ontologies.org.rdfs.ns.void as void
import ontologies.org.w3.ns.person as person
import ontologies.org.rdfs.sioc.ns as siocn
import ontologies.io.rww.cc.vocab as rww
import ontologies.com.megginson.exp.ns.airports as airport
import ontologies.org.w3.ns.solid.terms as solid
import ontologies.org.w3._2003.g.data_view as grddl
import ontologies.org.w3.ns.formats as formats
import ontologies.net.webns.mvcb as mvcb

